name: Android CI

env:
  # The name of the main module repository
  main_project_module: app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Set current date as env variable
      run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
    - name: Set repository name as env variable
      run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
    - name: Init gradle wrapper
      run: gradle wrapper
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build apk debug project
      run: ./gradlew assembleDebug
    - name: Upload APK Debug - ${{ env.repository_name }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.date_today }} - ${{ env.repository_name }} - APK(s) debug generated
        path: ${{ env.main_project_module }}/build/outputs/apk/debug/
